name: CI

on:
  push:
    branches: ["main", "work"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Run API Go tests
        run: go test ./...
        working-directory: apps/api
      - name: Run worker Go tests
        run: go test ./...
        working-directory: apps/worker
      - name: golangci-lint (API)
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.55
          working-directory: apps/api
      - name: golangci-lint (worker)
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.55
          working-directory: apps/worker

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable corepack
        run: corepack enable
      - name: Prepare pnpm
        run: corepack prepare pnpm@10.19.0 --activate
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build API image
        run: docker build -f apps/api/Dockerfile .
      - name: Build worker image
        run: docker build -f apps/worker/Dockerfile .
      - name: Build web image
        run: docker build -f apps/web/Dockerfile .
